Let's say we have an equation:

* 2x + y - z = 1
* 3x + 4y +2z = 13
* x - 5y -2z = 0

This can be represented as:

\begin{equation}
    \begin{bmatrix}
        2 &  1 & -1 \\
        3 &  4 &  2 \\
        1 & -5 & -2 \\
    \end{bmatrix}
    \begin{bmatrix}
        x \\
        y \\
        z \\
    \end{bmatrix}
    =
    \begin{bmatrix}
        1 \\
        13 \\
        0 \\
    \end{bmatrix}
\end{equation}

Which can be represented as:

X $\beta$ = y

#### Method 1: Inverse

$\beta$ = $X^{-1}y $

Provided it's possible to calculate the inverse

#### Method 2: Least Squares Solutions

X $\beta$ = y

$\beta = (X^TX)^{-1}X^Ty $

This provides the best possible approximate answer, reduces $y - X \beta$ as much as possible to zero.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
X = np.array([ [2, 1, -1], [3, 4, 2], [1, -5, -2] ])
X

array([[ 2,  1, -1],
       [ 3,  4,  2],
       [ 1, -5, -2]])

In [4]:
y = np.array([1, 13, 0])
y

array([ 1, 13,  0])

In [7]:
X_inv = np.linalg.inv(X)

In [8]:
X_inv @ y

array([ 3., -1.,  4.])

In [9]:
X_lss = np.linalg.inv(X.T @ X) @ X.T
X_lss

array([[ 0.06451613,  0.22580645,  0.19354839],
       [ 0.25806452, -0.09677419, -0.22580645],
       [-0.61290323,  0.35483871,  0.16129032]])

In [10]:
X_lss @ y

array([ 3., -1.,  4.])

In [11]:
X_sol_direct = np.linalg.solve(X, y)
X_sol_direct

array([ 3., -1.,  4.])