## Eigendecomposition

$A v = w$

Where A is a matrix

$v$ is the eigenvector and $w$ is the $v$ scaled by the proportion of eigenvalue.

The above equation can be re-written as:

$AV = V\Lambda $

Where $V$ is the matrix of all eigenvectors and $\Lambda $ is the matrix of eigenvalues on the diagonals.

$\rightarrow$ $A = V\Lambda V^{-1}$

That's why eigendecomposition is also known as <i>Diagonalization</i>.

This can work only for square matrices.

If the matrix is symmetric, the decomposition will result in real valued eigendecomposition.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
M = np.random.randint(-5, 6, (5, 5))

In [5]:
eig_vals, eig_vecs = np.linalg.eig(M)
eig_vals, eig_vecs

(array([ 3.3063424 +6.17132444j,  3.3063424 -6.17132444j,
        -0.99838303+1.05154719j, -0.99838303-1.05154719j,
         7.38408126+0.j        ]),
 array([[-0.22261313-0.07426888j, -0.22261313+0.07426888j,
          0.42979998+0.22956228j,  0.42979998-0.22956228j,
         -0.03248523+0.j        ],
        [-0.1664787 +0.22869498j, -0.1664787 -0.22869498j,
          0.02184325-0.31237932j,  0.02184325+0.31237932j,
          0.69900874+0.j        ],
        [ 0.58270571+0.j        ,  0.58270571-0.j        ,
          0.28452755+0.08699423j,  0.28452755-0.08699423j,
         -0.6855248 +0.j        ],
        [-0.18494748+0.53837567j, -0.18494748-0.53837567j,
         -0.02655231-0.46068054j, -0.02655231+0.46068054j,
         -0.06791972+0.j        ],
        [ 0.14901538+0.42320861j,  0.14901538-0.42320861j,
         -0.60254432+0.j        , -0.60254432-0.j        ,
          0.18914057+0.j        ]]))

Let's create a symmetric matrix and check real valued decomposition

In [6]:
M = np.random.randint(-5, 6, (5, 6))
M = M@M.T

In [7]:
eig_vals, eig_vecs = np.linalg.eig(M)
eig_vals, eig_vecs

(array([113.71576315,   0.62817659,  21.77204872,  81.54487684,
         54.3391347 ]),
 array([[ 0.31546698,  0.40842208, -0.5957127 , -0.61435703,  0.03692979],
        [ 0.68137264, -0.69077988, -0.21827763,  0.1006206 , -0.02801538],
        [ 0.0743089 , -0.02444066,  0.1523758 , -0.06675576,  0.98295785],
        [-0.25024653, -0.46312482,  0.34082538, -0.77275062, -0.09791124],
        [ 0.60668507,  0.37540994,  0.67683153, -0.10412055, -0.14852135]]))

In [8]:
eig_vecs @ eig_vecs

array([[ 0.50968576,  0.15966134, -0.55224251,  0.35795319, -0.53068485],
       [-0.31412438,  0.70368217, -0.27304841, -0.54837912, -0.1757333 ],
       [ 0.63116293,  0.44343674,  0.62683128, -0.10904395,  0.01375383],
       [-0.23520187,  0.53050424, -0.02754408,  0.69172685,  0.42895293],
       [ 0.4334279 , -0.03561985, -0.47623171, -0.28420632,  0.70943753]])

In [9]:
M

array([[ 50,  22,   6,  25,  18],
       [ 22,  55,   3, -27,  43],
       [  6,   3,  54,  -2,   0],
       [ 25, -27,  -2,  59,  -5],
       [ 18,  43,   0,  -5,  54]])

In [16]:
print(np.round(np.diag(eig_vals) * np.diag(eig_vals), 1))

[[1.29313e+04 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 4.00000e-01 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 4.74000e+02 0.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 6.64960e+03 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 2.95270e+03]]


In [18]:
dps = np.zeros((5, 5))
for i in range(5):
    for j in range(5):
        dps[i, j] = np.dot(eig_vecs[:, i], eig_vecs[:, j])
np.round(dps, 5)

array([[ 1., -0., -0., -0.,  0.],
       [-0.,  1., -0., -0.,  0.],
       [-0., -0.,  1.,  0.,  0.],
       [-0., -0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])