In [10]:
import numpy as np
import scipy
import sympy as sp
from IPython.display import display, Math

In [2]:
# polynomial: 3x^2 + 2x - 1
coeffs = [3, 2, -1]
roots = np.roots(coeffs)
roots

array([-1.        ,  0.33333333])

In [3]:
x = sp.symbols('x')

In [4]:
pn = 3*x**2 + 2*x - 1

In [9]:
for root in roots:
    display(Math('\\text{At }x = %g, \\quad %s = %g' %(root, sp.latex(pn), pn.subs(x, root))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [12]:
coeffs = [2, 7 ,5]
roots = np.roots(coeffs)
roots

array([-2.5, -1. ])

In [13]:
coeffs = [2, 5 , 7]
roots = np.roots(coeffs)
roots

array([-1.25+1.39194109j, -1.25-1.39194109j])

In [14]:
coeffs = [2, 5 , 7]
roots = scipy.roots(coeffs)
roots

/anaconda/envs/py37_default/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: scipy.roots is deprecated and will be removed in SciPy 2.0.0, use numpy.roots instead
  


array([-1.25+1.39194109j, -1.25-1.39194109j])